// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://edrqvdsinanfqzsitkrb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkcnF2ZHNpbmFuZnF6c2l0a3JiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MDM1MjUsImV4cCI6MjA2NjQ3OTUyNX0.qFyz8aa4BWxHWiC361_9jXDwn2oc2Drcm4gwwYSR8XI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);